# Generated by Django 4.0.1 on 2022-05-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userinfo',
        ),
    ]
