# Generated by Django 4.0.1 on 2022-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300, verbose_name='user_name')),
                ('fav_genre', models.CharField(max_length=300, verbose_name='fav_genre')),
                ('fav_actor', models.CharField(max_length=300, verbose_name='fav_actor')),
                ('fav_actress', models.CharField(max_length=300, verbose_name='fav_actress')),
            ],
        ),
    ]
