# Generated by Django 4.0.1 on 2022-05-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300, verbose_name='Title')),
                ('Genres', models.TextField(verbose_name='Genres')),
                ('Cast', models.TextField(verbose_name='Cast')),
                ('Rating_average', models.FloatField(verbose_name='Rating_average')),
                ('Rating_Count', models.BigIntegerField(verbose_name='Rating_Count')),
                ('Production_companies', models.TextField(verbose_name='Production_companies')),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
