# Generated by Django 4.0.1 on 2022-05-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='movies',
        ),
    ]
