# Generated by Django 4.0.1 on 2022-05-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_movie_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='Cast',
        ),
        migrations.AddField(
            model_name='movies',
            name='Actor',
            field=models.TextField(default=0, verbose_name='Actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='Actress',
            field=models.TextField(default=0, verbose_name='Actress'),
            preserve_default=False,
        ),
    ]
