# Generated by Django 4.0.1 on 2022-05-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_movies_cast_movies_actor_movies_actress'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='url',
            field=models.URLField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
